"""Revised logic

Revision ID: 4167a8e88025
Revises: '1490fa8480b2'
Create Date: 2026-07-23 14:37:26.867530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4167a8e88025'
down_revision: Union[str, None] = '1490fa8480b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql
    
    # Create ENUM types
    achievement_position = postgresql.ENUM('winner', 'runner_up', 'special_mention', name='achievementposition')
    achievement_position.create(op.get_bind())
    
    grievance_category = postgresql.ENUM('event', 'committee', 'facility', 'other', name='grievancecategory')
    grievance_category.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('alumni', sa.Column('willing_to_mentor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('event_registrations', sa.Column('achievement_position', achievement_position, nullable=True))
    op.add_column('event_registrations', sa.Column('certificate_url_override', sa.String(), nullable=True))
    op.add_column('events', sa.Column('certificate_url_pattern', sa.String(), nullable=True))
    op.add_column('grievances', sa.Column('category', grievance_category, server_default='other', nullable=False))
    op.add_column('grievances', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('grievances', sa.Column('under_review_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grievances', 'under_review_at')
    op.drop_column('grievances', 'is_anonymous')
    op.drop_column('grievances', 'category')
    op.drop_column('events', 'certificate_url_pattern')
    op.drop_column('event_registrations', 'certificate_url_override')
    op.drop_column('event_registrations', 'achievement_position')
    op.drop_column('alumni', 'willing_to_mentor')
    op.drop_column('alumni', 'is_published')
    # ### end Alembic commands ###
    op.execute("DROP TYPE achievementposition")
    op.execute("DROP TYPE grievancecategory")
